Linklist : SDriverProg.o SLinklist.o
	gcc -o Linklist SDriverProg.o SLinklist.o
SDriverProg.o : SDriverProg.c
	gcc -c SDriverProg.c -o SDriverProg.o
SLinklist.o : SLinklist.c
	gcc -c SLinklist.c -o SLinklist.o 
